/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_transport.swing.formulaires;

import gestion_transport.swing.classes.Admin;
import gestion_transport.swing.classes.Session;
import gestion_transport.swing.gestions.GestionAdmin;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Vanilah
 */
public class FormulaireAdmin extends javax.swing.JFrame {
    
    private int id_coop;
    private boolean visible = false; // état pour savoir si le mot de passe est visible
    private ImageIcon iconVisible;
    private ImageIcon iconMasquee;
    /**
     * Creates new form FormulaireAdmin
     */
    public FormulaireAdmin(int id_coop) {
        initComponents();
        this.setLocationRelativeTo(null);
        panelAdmin.setPreferredSize(new Dimension(900, 500));
        this.pack();
        this.id_coop = id_coop;
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/AdminImg.png"));
        Image img = icon.getImage().getScaledInstance(lblAdminImg.getWidth(), lblAdminImg.getHeight(), Image.SCALE_SMOOTH);
        lblAdminImg.setIcon(new ImageIcon(img));
        
        // Optionnel : définir une icône œil 
        ImageIcon originalVisible = new ImageIcon(getClass().getResource("/images/seeyou.png"));
        ImageIcon originalMasquee = new ImageIcon(getClass().getResource("/images/notsee.png"));
        
        iconVisible = resizeIcon(originalVisible, 20, 20);
        iconMasquee = resizeIcon(originalMasquee, 20, 20);
        
        btnToggle.setIcon(iconMasquee);
        btnToggle.setBorderPainted(false);
        btnToggle.setContentAreaFilled(false);
        txtMdpAdmin.setEchoChar('*');
    }
    
    public FormulaireAdmin(){
        initComponents();
    }
    
    private ImageIcon resizeIcon(ImageIcon icon, int width, int height){
        Image img = icon.getImage();
        Image newImag = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        return new ImageIcon(newImag);
    }
    
    public void EffacerChampsAdmin(){
        txtNomAdmin.setText("");
        txtConAdmin.setText("");
        txtMdpAdmin.setText("");
    }
    
    public boolean verifierAdmin(){
        if(txtNomAdmin.getText().trim().isEmpty() || txtConAdmin.getText().trim().isEmpty() || txtMdpAdmin.getPassword().equals("")){
            JOptionPane.showMessageDialog(this, "Veuiller remplir tous les champs obligatoires", "Champs manquants", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if(!txtConAdmin.getText().matches("^(034|032|033|038|037)\\d{7}$")){
            JOptionPane.showMessageDialog(this, "Le contact doit comporter 10 chiffres et commencer par 034, 032, 033, 038 ou 037", "Numéro Invalide", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if(txtMdpAdmin.getPassword().length < 8){
            JOptionPane.showMessageDialog(this, "Le mot de passe doit comporter 8 caractères", "Mot de passe Invalide", JOptionPane.WARNING_MESSAGE);
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdmin = new javax.swing.JPanel();
        btnToggle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtConAdmin = new javax.swing.JTextField();
        lblAdminImg = new javax.swing.JLabel();
        txtNomAdmin = new javax.swing.JTextField();
        txtMdpAdmin = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAjoutAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Création Admin");

        btnToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToggleActionPerformed(evt);
            }
        });

        jLabel1.setText("ADMINISTRATEUR");

        txtConAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConAdminKeyTyped(evt);
            }
        });

        lblAdminImg.setText("jLabel5");

        txtNomAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomAdminActionPerformed(evt);
            }
        });
        txtNomAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomAdminKeyTyped(evt);
            }
        });

        jLabel2.setText("Nom");

        jLabel3.setText("Contact");

        jLabel4.setText("Mot de passe");

        btnAjoutAdmin.setText("Ajouter");
        btnAjoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdminLayout.createSequentialGroup()
                        .addComponent(lblAdminImg, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAjoutAdmin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminLayout.createSequentialGroup()
                                .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)
                                        .addComponent(txtNomAdmin)
                                        .addComponent(txtConAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelAdminLayout.createSequentialGroup()
                                        .addComponent(txtMdpAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)))))
                .addContainerGap())
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtConAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMdpAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAjoutAdmin)
                        .addGap(65, 65, 65))
                    .addGroup(panelAdminLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblAdminImg, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutAdminActionPerformed
        // TODO add your handling code here:
         if (!verifierAdmin()){
            return ;
        }
        else {
            String nom = txtNomAdmin.getText();
            String contact = txtConAdmin.getText();
            String mdp = new String(txtMdpAdmin.getPassword());
            
            Admin ad = new Admin(nom, contact, mdp, this.id_coop);
            try {
                GestionAdmin ga = new GestionAdmin();
                ga.insertAdmin(ad);
                EffacerChampsAdmin();
                JOptionPane.showMessageDialog(txtNomAdmin, "Insertion Admin réussi!!. On va vous rediriger pour valider la création de votre compte Admin. Merci!!");
                new FormulaireLoginAdmin().setVisible(true);
                dispose();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAjoutAdminActionPerformed

    private void txtNomAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomAdminActionPerformed

    private void btnToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleActionPerformed
        // TODO add your handling code here:
        visible = !visible;
        txtMdpAdmin.setEchoChar(visible ? (char) 0 : '*');
        btnToggle.setIcon(visible ? iconVisible : iconMasquee);
    }//GEN-LAST:event_btnToggleActionPerformed

    private void txtNomAdminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomAdminKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isLetterOrDigit(c) && c != ' '){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomAdminKeyTyped

    private void txtConAdminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConAdminKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
        if(txtConAdmin.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_txtConAdminKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaireAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaireAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaireAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaireAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormulaireAdmin fa = new FormulaireAdmin();
                fa.setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjoutAdmin;
    private javax.swing.JButton btnToggle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAdminImg;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JTextField txtConAdmin;
    private javax.swing.JPasswordField txtMdpAdmin;
    private javax.swing.JTextField txtNomAdmin;
    // End of variables declaration//GEN-END:variables
}
