/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_transport.swing.formulaires;

import gestion_transport.swing.classes.Cooperative;
import gestion_transport.swing.gestions.GestionCooperative;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Vanilah
 */
public class FormulaireCooperative extends javax.swing.JFrame {

    /**
     * Creates new form FormulaireCooperative
     */
    public FormulaireCooperative() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelCooper.setPreferredSize(new Dimension(900, 500));
        this.pack();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/Coop.png"));
        Image img = icon.getImage().getScaledInstance(lblCooperativeCreate.getWidth(), lblCooperativeCreate.getHeight(), Image.SCALE_SMOOTH);
        lblCooperativeCreate.setIcon(new ImageIcon(img));
    }

    private boolean verifierChamps(){
        if(txtNomCoop.getText().trim().isEmpty() || txtContact.getText().trim().isEmpty() || txtLogo.getText().trim().isEmpty() || txtNumPorte.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Veuiller remplir tous les champs obligatoires", "Champs manquants", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if(!txtContact.getText().trim().matches("^(034|032|033|038|037)\\d{7}$")){
            JOptionPane.showMessageDialog(this, "Le contact doit comporter 10 chiffres et commencer par 034, 032, 033, 038 ou 037", "Numéro Invalide", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    
    public void EffacerChamps(){
        txtNomCoop.setText("");
        txtContact.setText("");
        txtNumPorte.setText("");
        txtLogo.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCooper = new javax.swing.JPanel();
        btnRetourCoop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCooperativeCreate = new javax.swing.JLabel();
        txtNomCoop = new javax.swing.JTextField();
        txtNumPorte = new javax.swing.JTextField();
        txtLogo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAjoutCoop = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Création Coopérative");

        btnRetourCoop.setText("Retour");
        btnRetourCoop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourCoopActionPerformed(evt);
            }
        });

        jLabel1.setText("GERER VOTRE COOPERATIVE AVEC NOUS");

        jLabel4.setText("Contact");

        txtNomCoop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomCoopKeyTyped(evt);
            }
        });

        txtNumPorte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumPorteKeyTyped(evt);
            }
        });

        jLabel5.setText("Logo");

        jLabel3.setText("Numero porte");

        btnAjoutCoop.setText("Ajouter");
        btnAjoutCoop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutCoopActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom");

        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelCooperLayout = new javax.swing.GroupLayout(panelCooper);
        panelCooper.setLayout(panelCooperLayout);
        panelCooperLayout.setHorizontalGroup(
            panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCooperLayout.createSequentialGroup()
                .addGroup(panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCooperLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCooperativeCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(panelCooperLayout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addGroup(panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGroup(panelCooperLayout.createSequentialGroup()
                                .addComponent(btnRetourCoop)
                                .addGap(48, 48, 48)))
                        .addGap(25, 25, 25)
                        .addGroup(panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNomCoop)
                                .addComponent(txtNumPorte)
                                .addComponent(txtContact)
                                .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAjoutCoop))))
                .addGap(15, 15, 15))
        );
        panelCooperLayout.setVerticalGroup(
            panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCooperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCooperativeCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCooperLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addGroup(panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNomCoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNumPorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(panelCooperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRetourCoop)
                            .addComponent(btnAjoutCoop))))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(panelCooper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelCooper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjoutCoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutCoopActionPerformed
        // TODO add your handling code here:
         if (!verifierChamps()){
            return;
        }
        else {
            String nom = txtNomCoop.getText();
            String contact = txtContact.getText();
            String numporte = txtNumPorte.getText();
            String logo = txtLogo.getText();
            Cooperative cp = new Cooperative(nom, contact, logo, numporte);
            try {
                GestionCooperative gc = new GestionCooperative();
                int id_coop = gc.insertCoop(cp);
                EffacerChamps();
                JOptionPane.showMessageDialog(txtNomCoop, "Insertion Cooperative réussi!!");
                FormulaireAdmin fa = new FormulaireAdmin(id_coop);
                fa.setVisible(true);
                
                dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAjoutCoopActionPerformed

    private void btnRetourCoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourCoopActionPerformed
        // TODO add your handling code here:
        new FormulairePassageAdminCoop().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRetourCoopActionPerformed

    private void txtNomCoopKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomCoopKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isLetterOrDigit(c) && c != ' '){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomCoopKeyTyped

    private void txtNumPorteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumPorteKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNumPorteKeyTyped

    private void txtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
        if(txtContact.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_txtContactKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaireCooperative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaireCooperative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaireCooperative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaireCooperative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormulaireCooperative().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjoutCoop;
    private javax.swing.JButton btnRetourCoop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCooperativeCreate;
    private javax.swing.JPanel panelCooper;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtLogo;
    private javax.swing.JTextField txtNomCoop;
    private javax.swing.JTextField txtNumPorte;
    // End of variables declaration//GEN-END:variables
}
