/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_transport.swing.formulaires;

import gestion_transport.swing.classes.ReservationTemp;
import gestion_transport.swing.formulaires.panels.PanelChoixCooperative;
import gestion_transport.swing.formulaires.panels.PanelChoixSiege;
import gestion_transport.swing.formulaires.panels.PanelChoixTrajetEtDate;
import gestion_transport.swing.formulaires.panels.PanelFactureBillet;
import gestion_transport.swing.formulaires.panels.PanelInformationPassager;
import gestion_transport.swing.formulaires.panels.PanelPaiement;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Vanilah
 */
public class FormulaireReservationPassager extends javax.swing.JFrame {

    private JPanel panelPrincipal;
    private CardLayout cardLayout;
    public ReservationTemp temp = new ReservationTemp();
    public PanelChoixCooperative panelChoixCooperative;
    public PanelChoixSiege panelChoixSiege;
    public PanelInformationPassager infoclient;
    public PanelPaiement paiement;
    public PanelFactureBillet facture;
    /**
     * Creates new form FormulaireReservationPassager
     */
    public FormulaireReservationPassager() {
        setTitle("Réservation de voyage");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1000, 600);
        setLocationRelativeTo(null);
        cardLayout = new CardLayout();
        panelPrincipal = new JPanel(cardLayout);
        getContentPane().add(panelPrincipal, BorderLayout.CENTER);
        
        panelPrincipal.add(new PanelChoixTrajetEtDate(this), "choix_trajet_date");
        panelChoixCooperative = new PanelChoixCooperative(this);
        panelPrincipal.add(panelChoixCooperative, "choix_cooperative");
        panelChoixSiege = new PanelChoixSiege(this);
        panelPrincipal.add(panelChoixSiege, "choix_siege");
        infoclient = new PanelInformationPassager(this);
        panelPrincipal.add(infoclient, "info_passager");
        paiement = new PanelPaiement(this);
        panelPrincipal.add(paiement, "paiement");
        facture = new PanelFactureBillet(this);
        panelPrincipal.add(facture, "facture");
        
        //add(panelPrincipal);
        goTo("choix_trajet_date");
        
        setVisible(true);
    }
    
    public void goTo(String panelName){
        if(panelName.equals("choix_cooperative")){
            panelChoixCooperative.loadData();
        }
        if(panelName.equals("choix_siege")){
            panelChoixSiege.loadDataSiege();
        }
        if(panelName.equals("info_passager")){
            infoclient.loadDataPassager();
        }
        if(panelName.equals("paiement")){
            paiement.loadDataPaiem();
        }
        if(panelName.equals("facture")){
            facture.loadDataFacture();
        }
        CardLayout cl = (CardLayout) panelPrincipal.getLayout();
        cl.show(panelPrincipal, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelChoix = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Réservation de billet");

        panelChoix.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(panelChoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(521, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(panelChoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaireReservationPassager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaireReservationPassager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaireReservationPassager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaireReservationPassager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(() -> new FormulaireReservationPassager());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelChoix;
    // End of variables declaration//GEN-END:variables
}
