/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_transport.swing.formulaires;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Vanilah
 */
public class FormulairePassageAdminCoop extends javax.swing.JFrame {

    /**
     * Creates new form FormulairePassageAdminCoop
     */
    public FormulairePassageAdminCoop() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelAdminCoop.setPreferredSize(new Dimension(900, 500));
        this.pack();
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/passage.png"));
        Image img = icon.getImage().getScaledInstance(lblImagePassage.getWidth(), lblImagePassage.getHeight(), Image.SCALE_SMOOTH);
        lblImagePassage.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdminCoop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblImagePassage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSeConnecter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPassageCreation = new javax.swing.JButton();
        btnRetourPrincipale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GRF - Coopérative");

        jLabel1.setText("Nous vous remércions d'être là.");

        lblImagePassage.setText("jLabel1");

        jLabel3.setText("Sinon connectez vous.");

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel4.setText("GARE ROUTIERE FIANARANTSOA");

        btnSeConnecter.setText("Se Connecter");
        btnSeConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeConnecterActionPerformed(evt);
            }
        });

        jLabel2.setText("Créer le compte de votre Coopérative si vous n'en avez pas déjà une !");

        btnPassageCreation.setText("Créer Coopérative");
        btnPassageCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassageCreationActionPerformed(evt);
            }
        });

        btnRetourPrincipale.setText("Retour");
        btnRetourPrincipale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourPrincipaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdminCoopLayout = new javax.swing.GroupLayout(panelAdminCoop);
        panelAdminCoop.setLayout(panelAdminCoopLayout);
        panelAdminCoopLayout.setHorizontalGroup(
            panelAdminCoopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminCoopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagePassage, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelAdminCoopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminCoopLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4))
                    .addGroup(panelAdminCoopLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelAdminCoopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelAdminCoopLayout.createSequentialGroup()
                                .addComponent(btnSeConnecter, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRetourPrincipale)
                                .addGap(18, 18, 18)
                                .addComponent(btnPassageCreation))
                            .addGroup(panelAdminCoopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panelAdminCoopLayout.setVerticalGroup(
            panelAdminCoopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminCoopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminCoopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagePassage, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminCoopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(147, 147, 147)
                        .addGroup(panelAdminCoopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPassageCreation)
                            .addComponent(btnSeConnecter)
                            .addComponent(btnRetourPrincipale))
                        .addGap(50, 50, 50)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(panelAdminCoop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(panelAdminCoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeConnecterActionPerformed
        // TODO add your handling code here:
        new FormulaireLoginAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSeConnecterActionPerformed

    private void btnPassageCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassageCreationActionPerformed
        // TODO add your handling code here:
        new FormulaireCooperative().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPassageCreationActionPerformed

    private void btnRetourPrincipaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourPrincipaleActionPerformed
        // TODO add your handling code here:
        new FormulairePrincipale().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRetourPrincipaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulairePassageAdminCoop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulairePassageAdminCoop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulairePassageAdminCoop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulairePassageAdminCoop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulairePassageAdminCoop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPassageCreation;
    private javax.swing.JButton btnRetourPrincipale;
    private javax.swing.JButton btnSeConnecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblImagePassage;
    private javax.swing.JPanel panelAdminCoop;
    // End of variables declaration//GEN-END:variables
}
