/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_transport.swing.formulaires;

import gestion_transport.swing.classes.Session;
import gestion_transport.swing.formulaires.panels.PanelAccueil;
import gestion_transport.swing.formulaires.panels.PanelFactureAdmin;
import gestion_transport.swing.formulaires.panels.PanelReservation;
import gestion_transport.swing.formulaires.panels.PanelSiege;
import gestion_transport.swing.formulaires.panels.PanelTrajet;
import gestion_transport.swing.formulaires.panels.PanelVehicule;
import gestion_transport.swing.gestions.GestionAccueil;
import java.sql.ResultSet;
import java.awt.BorderLayout;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vanilah
 */
public final class FormulaireAccueilAdmin extends javax.swing.JFrame {

    private PanelFactureAdmin facturePanel;
    private PanelReservation panelReservation;
    //PanelFactureAdmin facturePanel = new PanelFactureAdmin();
    //PanelReservation panelReservation = new PanelReservation(facturePanel);
    /**
     * Creates new form FormulaireAcceuilAdmin
     */
    public FormulaireAccueilAdmin() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setLayout(new BorderLayout());
        
        facturePanel = new PanelFactureAdmin();
        panelReservation = new PanelReservation(facturePanel);
        
        panelPrincipal.setLayout(new BorderLayout());
        panelPrincipal.add(new PanelAccueil(), BorderLayout.CENTER);
        jlblCooperative.setText("Cooperative : " + Session.nomCoop);
        lblNomAdmin.setText("Admin : " + Session.nomAdmin);
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/adminAd.png"));
        Image img = icon.getImage().getScaledInstance(lblAdmin.getWidth(), lblAdmin.getHeight(), Image.SCALE_SMOOTH);
        lblAdmin.setIcon(new ImageIcon(img));
        updateDate();
    }
    
    
    public void updateDate(){
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        jlblDate.setText(sdf.format(new Date()));
    }
    
    /* void verifierAlertesDepart() {
        try {
            GestionAccueil ga = new GestionAccueil();
             ResultSet rs = ga.selectAlerte();
            while (rs.next()) {
                JOptionPane.showMessageDialog(this, "ALERTE : Le trajet " + rs.getString("depart") + " -> " + rs.getString("arrivee") +
                                          " part dans moins d'une heure à " + rs.getTime("heure_depart"));
                }
            } catch (Exception e) {
            e.printStackTrace();
        }
    }*/

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBouton = new javax.swing.JPanel();
        btnTrajet = new javax.swing.JButton();
        btnAcceuil = new javax.swing.JButton();
        btnVehicule = new javax.swing.JButton();
        btnSiege = new javax.swing.JButton();
        btnReservation = new javax.swing.JButton();
        btnDeconnexion = new javax.swing.JButton();
        lblAdmin = new javax.swing.JLabel();
        lblNomAdmin = new javax.swing.JLabel();
        PanelTitre = new javax.swing.JPanel();
        jlblCooperative = new javax.swing.JLabel();
        jlblDate = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMINISTRATEUR");

        PanelBouton.setBackground(new java.awt.Color(204, 255, 255));
        PanelBouton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        btnTrajet.setText("Trajet");
        btnTrajet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrajetActionPerformed(evt);
            }
        });

        btnAcceuil.setText("Acceuil");
        btnAcceuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceuilActionPerformed(evt);
            }
        });

        btnVehicule.setText("Vehicule");
        btnVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculeActionPerformed(evt);
            }
        });

        btnSiege.setText("Siège");
        btnSiege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiegeActionPerformed(evt);
            }
        });

        btnReservation.setText("Reservation");
        btnReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationActionPerformed(evt);
            }
        });

        btnDeconnexion.setText("Deconnexion");
        btnDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeconnexionActionPerformed(evt);
            }
        });

        lblNomAdmin.setText("AdminNom");

        javax.swing.GroupLayout PanelBoutonLayout = new javax.swing.GroupLayout(PanelBouton);
        PanelBouton.setLayout(PanelBoutonLayout);
        PanelBoutonLayout.setHorizontalGroup(
            PanelBoutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBoutonLayout.createSequentialGroup()
                .addGroup(PanelBoutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelBoutonLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(PanelBoutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReservation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeconnexion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSiege, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelBoutonLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelBoutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrajet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAcceuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVehicule, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
            .addGroup(PanelBoutonLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblNomAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBoutonLayout.setVerticalGroup(
            PanelBoutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBoutonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomAdmin)
                .addGap(42, 42, 42)
                .addComponent(btnAcceuil)
                .addGap(29, 29, 29)
                .addComponent(btnTrajet)
                .addGap(28, 28, 28)
                .addComponent(btnVehicule)
                .addGap(35, 35, 35)
                .addComponent(btnSiege)
                .addGap(37, 37, 37)
                .addComponent(btnReservation)
                .addGap(31, 31, 31)
                .addComponent(btnDeconnexion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlblCooperative.setText("Logo");

        jlblDate.setText("jLabel2");

        javax.swing.GroupLayout PanelTitreLayout = new javax.swing.GroupLayout(PanelTitre);
        PanelTitre.setLayout(PanelTitreLayout);
        PanelTitreLayout.setHorizontalGroup(
            PanelTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTitreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblCooperative, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblDate)
                .addGap(73, 73, 73))
        );
        PanelTitreLayout.setVerticalGroup(
            PanelTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTitreLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCooperative)
                    .addComponent(jlblDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        panelPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1124, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelBouton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(PanelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelBouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrajetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrajetActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setLayout(new BorderLayout());
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelTrajet(), BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnTrajetActionPerformed

    private void btnAcceuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceuilActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setLayout(new BorderLayout());
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelAccueil(), BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnAcceuilActionPerformed

    private void btnVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculeActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setLayout(new BorderLayout());
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelVehicule(), BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnVehiculeActionPerformed

    private void btnSiegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiegeActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setLayout(new BorderLayout());
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelSiege(), BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnSiegeActionPerformed

    private void btnReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setLayout(new BorderLayout());
        panelPrincipal.removeAll();
        panelPrincipal.add(panelReservation, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnReservationActionPerformed

    private void btnDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeconnexionActionPerformed
        // TODO add your handling code here:
        int choix = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment vous deconnecter ? ", "Deconnexion", JOptionPane.YES_NO_OPTION);
        if(choix == JOptionPane.YES_OPTION){
            new FormulairePrincipale().setVisible(true);
            dispose(); 
        }
    }//GEN-LAST:event_btnDeconnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaireAccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaireAccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaireAccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaireAccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulaireAccueilAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBouton;
    private javax.swing.JPanel PanelTitre;
    private javax.swing.JButton btnAcceuil;
    private javax.swing.JButton btnDeconnexion;
    private javax.swing.JButton btnReservation;
    private javax.swing.JButton btnSiege;
    private javax.swing.JButton btnTrajet;
    private javax.swing.JButton btnVehicule;
    private javax.swing.JLabel jlblCooperative;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblNomAdmin;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
