/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_transport.swing.formulaires;

import gestion_transport.swing.classes.Admin;
import gestion_transport.swing.classes.Session;
import gestion_transport.swing.gestions.GestionAdmin;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Vanilah
 */
public class FormulaireLoginAdmin extends javax.swing.JFrame {

    private boolean visible = false; // état pour savoir si le mot de passe est visible
    private ImageIcon iconVisible;
    private ImageIcon iconMasquee;
    /**
     * Creates new form FormulaireLoginAdmin
     */
    public FormulaireLoginAdmin() {
        initComponents();
        //CENTRAGE DU PANEL LOGIN
        this.setLocationRelativeTo(null);
        panelLogin.setPreferredSize(new Dimension(900, 500));
        setContentPane(panelLogin);
        pack();
                
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/login1.png"));
        Image img = icon.getImage().getScaledInstance(lblImageLogin.getWidth(), lblImageLogin.getHeight(), Image.SCALE_SMOOTH);
        lblImageLogin.setIcon(new ImageIcon(img));
        ImageIcon iconN = new ImageIcon(getClass().getResource("/images/admin.png"));
        Image imgN = iconN.getImage().getScaledInstance(lblNomAd.getWidth(), lblNomAd.getHeight(), Image.SCALE_SMOOTH);
        lblNomAd.setIcon(new ImageIcon(imgN));
        ImageIcon iconMdp = new ImageIcon(getClass().getResource("/images/mdp.png"));
        Image imgMdp = iconMdp.getImage().getScaledInstance(lblMdpAd.getWidth(), lblMdpAd.getHeight(), Image.SCALE_SMOOTH);
        lblMdpAd.setIcon(new ImageIcon(imgMdp));

        // Optionnel : définir une icône œil 
        ImageIcon originalVisible = new ImageIcon(getClass().getResource("/images/seeyou.png"));
        ImageIcon originalMasquee = new ImageIcon(getClass().getResource("/images/notsee.png"));
        
        iconVisible = resizeIcon(originalVisible, 20, 20);
        iconMasquee = resizeIcon(originalMasquee, 20, 20);
        
        btnTogglePassword.setIcon(iconMasquee);
        btnTogglePassword.setBorderPainted(false);
        btnTogglePassword.setContentAreaFilled(false);
        txtMdpAd.setEchoChar('*');
    }
    
    private ImageIcon resizeIcon(ImageIcon icon, int width, int height){
        Image img = icon.getImage();
        Image newImag = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        return new ImageIcon(newImag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        lblImageLogin = new javax.swing.JLabel();
        lblNomAd = new javax.swing.JLabel();
        lblMdpAdmin = new javax.swing.JLabel();
        lblMdpAd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMdpAd = new javax.swing.JPasswordField();
        btnTogglePassword = new javax.swing.JButton();
        lblNomAdmin = new javax.swing.JLabel();
        btnConnexAdmin = new javax.swing.JButton();
        btnRetourLogin = new javax.swing.JButton();
        txtNomAd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connexion");

        lblNomAd.setText("  ");

        lblMdpAdmin.setText("Mot de passe");

        lblMdpAd.setText("  ");

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel1.setText("ADMINISTRATEUR");

        btnTogglePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTogglePasswordActionPerformed(evt);
            }
        });

        lblNomAdmin.setText("Nom");

        btnConnexAdmin.setText("Se Connecter");
        btnConnexAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnexAdminActionPerformed(evt);
            }
        });

        btnRetourLogin.setText("Retour");
        btnRetourLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourLoginActionPerformed(evt);
            }
        });

        txtNomAd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomAdKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImageLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLoginLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(lblMdpAd, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblMdpAdmin))
                        .addGroup(panelLoginLayout.createSequentialGroup()
                            .addComponent(lblNomAd, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblNomAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNomAd, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addComponent(txtMdpAd, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTogglePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(btnRetourLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConnexAdmin)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomAd))
                        .addGap(18, 18, 18)
                        .addComponent(txtNomAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMdpAdmin)
                            .addComponent(lblMdpAd))
                        .addGap(18, 18, 18)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTogglePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMdpAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConnexAdmin)
                            .addComponent(btnRetourLogin)))
                    .addComponent(lblImageLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnexAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnexAdminActionPerformed
        // TODO add your handling code here:
        if(txtNomAd.getText().trim().isEmpty() || txtMdpAd.getPassword().equals("")){
            JOptionPane.showMessageDialog(this, "Veuiller remplir tous les champs obligatoires", "Champs manquants", JOptionPane.WARNING_MESSAGE);
        }
        else{
            String nom = txtNomAd.getText();
            String mdp = new String(txtMdpAd.getPassword());
            Admin ad = new Admin(nom, mdp);
            try{
                GestionAdmin ga = new GestionAdmin();
                ResultSet rst = ga.verifAdmin(ad);
                if(rst.next()){
                    Session.idAdmin = rst.getInt("id_admin");
                    Session.idCoop = rst.getInt("id_cooper");
                    Session.nomAdmin = rst.getString("a.nom_admin");
                    Session.nomCoop = rst.getString("c.nom_coo"); 
                    //System.out.println(Session.nomCoop);
                    JOptionPane.showMessageDialog(this, "Connexion réussie");
                    new FormulaireAccueilAdmin().setVisible(true);
                    dispose();
                }
                
                else{
                    JOptionPane.showMessageDialog(this, "Identifiants incorrects !");
                }
                
            }
            catch(Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnConnexAdminActionPerformed

    private void btnTogglePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTogglePasswordActionPerformed
        // TODO add your handling code here:
        visible = !visible;
        txtMdpAd.setEchoChar(visible ? (char) 0 : '*');
        btnTogglePassword.setIcon(visible ? iconVisible : iconMasquee);

    }//GEN-LAST:event_btnTogglePasswordActionPerformed

    private void btnRetourLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourLoginActionPerformed
        // TODO add your handling code here:
        new FormulairePassageAdminCoop().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRetourLoginActionPerformed

    private void txtNomAdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomAdKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isLetterOrDigit(c) && c != ' '){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomAdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaireLoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaireLoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaireLoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaireLoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        }
        catch(Exception ex){
            System.err.println("Erreur Flatlaf");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulaireLoginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnexAdmin;
    private javax.swing.JButton btnRetourLogin;
    private javax.swing.JButton btnTogglePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImageLogin;
    private javax.swing.JLabel lblMdpAd;
    private javax.swing.JLabel lblMdpAdmin;
    private javax.swing.JLabel lblNomAd;
    private javax.swing.JLabel lblNomAdmin;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField txtMdpAd;
    private javax.swing.JTextField txtNomAd;
    // End of variables declaration//GEN-END:variables
}
