/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion_transport.swing.formulaires.panels;

import java.sql.ResultSet;
import gestion_transport.swing.formulaires.FormulaireReservationPassager;
import gestion_transport.swing.gestions.GestionCooperative;
import java.awt.Image;
import java.sql.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Vanilah
 */
public class PanelChoixCooperative extends javax.swing.JPanel {

    private FormulaireReservationPassager parent;
    /**
     * Creates new form PanelChoixCooperative
     */
    public PanelChoixCooperative(FormulaireReservationPassager parent) {
        initComponents();
        this.parent = parent;
    }
    
    public void loadData(){
        if(parent.temp.dateDepart == null){
            return;
        }
        else{
            remplirCooperatives();
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/ChoixCoop.png"));
            Image img = icon.getImage().getScaledInstance(500, 250, Image.SCALE_SMOOTH);
            lblChoixCooperative.setIcon(new ImageIcon(img));
        }

    }
    
    private void remplirCooperatives() {
        //cbCooperative.removeAllItems();
        try{
            cbChoixCooperative.removeAllItems();
            System.out.println(parent.temp.villeArrivee);
            System.out.println(parent.temp.dateDepart);
            GestionCooperative gc = new GestionCooperative();
            ResultSet rs = gc.getCooperative(parent.temp.villeArrivee, Date.valueOf(parent.temp.dateDepart));
            while (rs.next()) {
                int id_cooper = rs.getInt("c.id_cooper");
                String nom = rs.getString("c.nom_coo");
                cbChoixCooperative.addItem(id_cooper + " - " + nom);
            }
        }catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur de chargement des coopératives");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbChoixCooperative = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnSuivantCoop = new javax.swing.JButton();
        btnRetourCoop = new javax.swing.JButton();
        lblChoixCooperative = new javax.swing.JLabel();

        jLabel1.setText("Voici la liste de coopérative qui propose le voyage pour cette date");

        cbChoixCooperative.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Coopérative");

        btnSuivantCoop.setText("Suivant");
        btnSuivantCoop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantCoopActionPerformed(evt);
            }
        });

        btnRetourCoop.setText("Retour");
        btnRetourCoop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourCoopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnRetourCoop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSuivantCoop)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel2)
                                .addGap(45, 45, 45)
                                .addComponent(cbChoixCooperative, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(lblChoixCooperative, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbChoixCooperative, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52)
                .addComponent(lblChoixCooperative, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuivantCoop)
                    .addComponent(btnRetourCoop))
                .addGap(115, 115, 115))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuivantCoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantCoopActionPerformed
        // TODO add your handling code here:
        if (cbChoixCooperative.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une coopérative.");
            return;
        }

        String selected = cbChoixCooperative.getSelectedItem().toString();
        int idCoop = Integer.parseInt(selected.split(" - ")[0]);
        String nom = selected.split(" - ")[1].trim();
        parent.temp.cooperative = nom;
        parent.temp.idCoop = idCoop;

        parent.goTo("choix_siege"); // Passage au panel suivant
    }//GEN-LAST:event_btnSuivantCoopActionPerformed

    private void btnRetourCoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourCoopActionPerformed
        // TODO add your handling code here:
        parent.goTo("choix_trajet_date");
    }//GEN-LAST:event_btnRetourCoopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetourCoop;
    private javax.swing.JButton btnSuivantCoop;
    private javax.swing.JComboBox<String> cbChoixCooperative;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblChoixCooperative;
    // End of variables declaration//GEN-END:variables
}
