/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion_transport.swing.formulaires.panels;

import gestion_transport.swing.formulaires.FormulaireReservationPassager;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Vanilah
 */
public class PanelInformationPassager extends javax.swing.JPanel {

    public FormulaireReservationPassager parent;
    /**
     * Creates new form PanelInformationPassager
     */
    public PanelInformationPassager(FormulaireReservationPassager parent) {
        initComponents();
        this.parent = parent;
        
    }
    
    public void loadDataPassager(){
        lblNbBillet.setText(String.valueOf(this.parent.temp.nb_billet));
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/imgInfoCli.png"));
        Image img = icon.getImage().getScaledInstance(150, 140, Image.SCALE_SMOOTH);
        lblInfoCli.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomCli = new javax.swing.JTextField();
        txtPrenomCli = new javax.swing.JTextField();
        txtContactCli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNbBillet = new javax.swing.JLabel();
        btnSuivantPassager = new javax.swing.JButton();
        btnRetourPassager = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblInfoCli = new javax.swing.JLabel();

        txtNomCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomCliKeyTyped(evt);
            }
        });

        txtPrenomCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrenomCliKeyTyped(evt);
            }
        });

        txtContactCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactCliKeyTyped(evt);
            }
        });

        jLabel1.setText("Votre nom");

        jLabel2.setText("Votre Prénom(s)");

        jLabel3.setText("Votre numéro téléphone");

        jLabel4.setText("Nombre de vos billets");

        btnSuivantPassager.setText("Suivant");
        btnSuivantPassager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantPassagerActionPerformed(evt);
            }
        });

        btnRetourPassager.setText("Retour");
        btnRetourPassager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourPassagerActionPerformed(evt);
            }
        });

        jLabel5.setText("Veuillez saisir vos informations exactes.");

        lblInfoCli.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnRetourPassager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                .addComponent(btnSuivantPassager)
                .addGap(207, 207, 207))
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomCli)
                    .addComponent(txtPrenomCli)
                    .addComponent(txtContactCli)
                    .addComponent(lblNbBillet, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInfoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrenomCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContactCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblInfoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNbBillet, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuivantPassager)
                    .addComponent(btnRetourPassager))
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuivantPassagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantPassagerActionPerformed
        // TODO add your handling code here:
        String nom = txtNomCli.getText().trim();
        String prenom = txtPrenomCli.getText().trim();
        String contact = txtContactCli.getText().trim();

        if (nom.isEmpty() || prenom.isEmpty() || contact.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs.");
            return;
        }
        if(!contact.matches("^(034|032|033|038|037)\\d{7}$")){
            JOptionPane.showMessageDialog(this, "Le contact doit comporter 10 chiffres et commencer par 034, 032, 033, 038 ou 037", "Numéro Invalide", JOptionPane.WARNING_MESSAGE);
            return;
        }

        parent.temp.nomClient = nom;
        parent.temp.prenomClient = prenom;
        parent.temp.contactClient = contact;

        parent.goTo("paiement");

    }//GEN-LAST:event_btnSuivantPassagerActionPerformed

    private void btnRetourPassagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourPassagerActionPerformed
        // TODO add your handling code here:
        parent.goTo("choix_siege");
    }//GEN-LAST:event_btnRetourPassagerActionPerformed

    private void txtNomCliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomCliKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isLetter(c) && c != ' '){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomCliKeyTyped

    private void txtPrenomCliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrenomCliKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isLetter(c) && c != ' '){
            evt.consume();
        }
    }//GEN-LAST:event_txtPrenomCliKeyTyped

    private void txtContactCliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactCliKeyTyped
        // TODO add your handling code here
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
        if(txtContactCli.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_txtContactCliKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetourPassager;
    private javax.swing.JButton btnSuivantPassager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblInfoCli;
    private javax.swing.JLabel lblNbBillet;
    private javax.swing.JTextField txtContactCli;
    private javax.swing.JTextField txtNomCli;
    private javax.swing.JTextField txtPrenomCli;
    // End of variables declaration//GEN-END:variables
}
