/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion_transport.swing.formulaires.panels;

import gestion_transport.swing.classes.Trajet;
import gestion_transport.swing.gestions.GestionAccueil;
import gestion_transport.swing.gestions.GestionReservation;
import gestion_transport.swing.gestions.GestionTrajet;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Vanilah
 */
public final class PanelAccueil extends javax.swing.JPanel {
    
    private boolean iscbReady = false;

    //JComboBox<Trajet> cbTrajet;
    /**
     * Creates new form PanelAcceuil
     */
    public PanelAccueil() {
        initComponents();
        //cbTrajet.setModel(new DefaultComboBoxModel<Trajet>());
        chargerInfos();
        alerteTrajet();
        chargerTrajet();
    }

    public void alerteTrajet(){
        try{
            GestionAccueil gac = new GestionAccueil();
            ResultSet rs = gac.selectAlerte();
            while(rs.next()){
                JOptionPane.showMessageDialog(this, "ALERTE : Le trajet "+ rs.getString("ville-dep") + "->" + rs.getString("ville_arr")+ "part dans moins d'une heure à " + rs.getTime("heure_dep"));
                }
        }            
        catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    public void chargerTrajet(){
        cbTrajet.removeAllItems();
        try{
            cbTrajet.addItem(-1+" - "+ "Sélectionner un trajet");
            GestionTrajet gt = new GestionTrajet();
            ResultSet rs = gt.getTrajet();
            while(rs.next()){
                int id_traj = rs.getInt("id_traj");
                String ville_arr = rs.getString("ville_arr");
                cbTrajet.addItem(id_traj+" - "+ville_arr);
                
                iscbReady = true;
            }
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }
    
    public void afficherCourbe(int id_traj){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try{
            GestionReservation gr = new GestionReservation();
            ResultSet rs = gr.getJourTrajet(id_traj);
            while(rs.next()){
                String jour = rs.getString("jour");
                int total = rs.getInt("total");
                dataset.addValue(total, "Reservations", jour);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        JFreeChart chart = ChartFactory.createLineChart("Progression des reservations", "jour", "total", dataset);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(600,400));
        
        panelCourbe.removeAll();
        panelCourbe.setLayout(new BorderLayout());
        panelCourbe.add(chartPanel, BorderLayout.CENTER);
        panelCourbe.revalidate();
        panelCourbe.repaint();
    }
    
    private void chargerInfos(){
        try{
            GestionAccueil gac = new GestionAccueil();
            ResultSet rs = gac.selectTrajet();
            DefaultTableModel model = new DefaultTableModel();
            tInfosTrajet.setModel(model);
            model.setColumnIdentifiers(new String[]{"ID Trajet", "Départ", "Arrivée", "Matricule Vahicule"});
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getInt("id_traj"),
                    rs.getString("ville_dep"),
                    rs.getString("ville_arr"),
                    rs.getString("immatriculation")
                });
            }            
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tInfosTrajet = new javax.swing.JTable();
        panelCourbe = new javax.swing.JPanel();
        cbTrajet = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        tInfosTrajet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tInfosTrajet);

        javax.swing.GroupLayout panelCourbeLayout = new javax.swing.GroupLayout(panelCourbe);
        panelCourbe.setLayout(panelCourbeLayout);
        panelCourbeLayout.setHorizontalGroup(
            panelCourbeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        panelCourbeLayout.setVerticalGroup(
            panelCourbeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        cbTrajet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item1", "item2", "item3", "item4" }));
        cbTrajet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrajetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbTrajet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addComponent(panelCourbe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbTrajet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(panelCourbe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbTrajetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrajetActionPerformed
        // TODO add your handling code here:
        if(!iscbReady)return;
        
        String selected = cbTrajet.getSelectedItem().toString();
        
        if (cbTrajet.getSelectedItem() == null || selected.equals("-1 - Sélectionner un trajet")) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un trajet.");
            return;
        }

        int id_traj = Integer.parseInt(selected.split(" - ")[0]);
        afficherCourbe(id_traj);
    }//GEN-LAST:event_cbTrajetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTrajet;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCourbe;
    private javax.swing.JTable tInfosTrajet;
    // End of variables declaration//GEN-END:variables
}
