/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion_transport.swing.formulaires.panels;

import gestion_transport.swing.formulaires.FormulaireReservationPassager;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import com.sun.jdi.connect.spi.Connection;
import gestion_transport.swing.classes.ReservationTemp;
import gestion_transport.swing.formulaires.FormulairePrincipale;
import javax.swing.*;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.util.stream.Collectors;


/**
 *
 * @author Vanilah
 */
public class PanelFactureBillet extends javax.swing.JPanel {

    public FormulaireReservationPassager parent;
    /**
     * Creates new form PanelFactureBillet
     */
    public PanelFactureBillet(FormulaireReservationPassager parent) {
        initComponents();
        this.parent = parent;
    }
    
    public void afficherInfos() {
        ReservationTemp temp = parent.temp;
        String resume = """
                        COOPERATIVE : %s 
                        
                CLIENT : %s %s
                CONTACT : %s
                TRAJET : %s - %s
                DATE : %s
                HEURE DE DEPART: %s
                NOMBRE DE BILLETS : %d
                MONTANT PAYÉ : %.2f Ar
                TRANSACTION ID : %s
                SIÈGES : %s
                """.formatted(
                temp.cooperative, temp.nomClient, temp.prenomClient, temp.contactClient,
                temp.villeDepart, temp.villeArrivee, temp.dateDepart.toString(), temp.heureDepart,
                temp.nb_billet, temp.montantPaye,
                temp.transactionId,
                String.join(", ", temp.placesChoisies.stream().map(String::valueOf).toList())
        );
        txtResume.setText(resume);
    }

    public void loadDataFacture(){
        txtResume.setEditable(false);
        afficherInfos();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResume = new javax.swing.JTextArea();
        btnGenererPDF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        txtResume.setColumns(20);
        txtResume.setRows(5);
        jScrollPane1.setViewportView(txtResume);

        btnGenererPDF.setText("Génerer Billet");
        btnGenererPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenererPDFActionPerformed(evt);
            }
        });

        jLabel1.setText("Prévisualisation de votre Billet. ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenererPDF)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenererPDF)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenererPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenererPDFActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Enregistrer la facture");
        chooser.setSelectedFile(new java.io.File("facture_" + parent.temp.transactionId + ".pdf"));
    
        int userSelection = chooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = chooser.getSelectedFile();

            try {
                Document doc = new Document();
                String path = "facture_" + parent.temp.transactionId + ".pdf";
                PdfWriter.getInstance(doc, new FileOutputStream(path));
                doc.open();
                doc.add(new Paragraph("FACTURE DE RÉSERVATION", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18)));
                doc.add(new Paragraph(" "));
                doc.add(new Paragraph(txtResume.getText()));
                doc.close();

                JOptionPane.showMessageDialog(this, "Facture générée : " + path);
                new FormulairePrincipale().setVisible(true);
                SwingUtilities.getWindowAncestor(this).dispose();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erreur lors de la génération du PDF.");
            }
        }
    }//GEN-LAST:event_btnGenererPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenererPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResume;
    // End of variables declaration//GEN-END:variables
}
