/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package gestion_transport.swing.formulaires.panels;

import gestion_transport.swing.formulaires.FormulaireReservationPassager;
import gestion_transport.swing.gestions.GestionSiege;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.*;
import javax.swing.JCheckBox;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Vanilah
 */
public class PanelChoixSiege extends javax.swing.JPanel {

    public FormulaireReservationPassager parent;
    private List<JCheckBox> checkBoxes = new ArrayList<>();
    
    /** Creates new form PanelChoixSiege */
    public PanelChoixSiege(FormulaireReservationPassager parent) {
        initComponents();
        this.parent = parent;
        
    }
    
    public void loadDataSiege(){
        if(parent.temp.dateDepart == null){
            return;
        }
        else{
            panelSiege.setMaximumSize(new Dimension(400, 200));
            panelSiege.setLayout(new GridLayout(0, 5, 10, 10));
            chargerSiegesDisponibles();
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/ChoixSiege.png"));
            Image img = icon.getImage().getScaledInstance(500, 300, Image.SCALE_SMOOTH);
            lblChoxSiege.setIcon(new ImageIcon(img));
        }

    }
    
    private void chargerSiegesDisponibles() {
        panelSiege.removeAll();
        checkBoxes.clear();

        try{
            GestionSiege gs = new GestionSiege();
            ResultSet rs = gs.selectSiege(parent.temp.villeArrivee, java.sql.Date.valueOf(parent.temp.dateDepart), parent.temp.idCoop);
            if(!rs.next()){
                JOptionPane.showMessageDialog(this, "Aucun siège disponible pour cette coopérative");
                return;
            }
            do{
                int idSiege = rs.getInt("s.id_siege");
                String numero = rs.getString("s.num_siege");

                JCheckBox cb = new JCheckBox(numero);
                cb.putClientProperty("id_siege", idSiege);
                checkBoxes.add(cb);
                panelSiege.add(cb);
            }while (rs.next());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur lors du chargement des sièges");
        }

        panelSiege.revalidate();
        panelSiege.repaint();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSiege = new javax.swing.JPanel();
        btnSuivantSiege = new javax.swing.JButton();
        btnRetourSiege = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblChoxSiege = new javax.swing.JLabel();

        javax.swing.GroupLayout panelSiegeLayout = new javax.swing.GroupLayout(panelSiege);
        panelSiege.setLayout(panelSiegeLayout);
        panelSiegeLayout.setHorizontalGroup(
            panelSiegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        panelSiegeLayout.setVerticalGroup(
            panelSiegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        btnSuivantSiege.setText("Suivant");
        btnSuivantSiege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantSiegeActionPerformed(evt);
            }
        });

        btnRetourSiege.setText("Retour");
        btnRetourSiege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourSiegeActionPerformed(evt);
            }
        });

        jLabel1.setText("Liste des sièges encore disponibles.");

        jLabel2.setText("Cochez le numéro de siège de votre choix !");

        lblChoxSiege.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblChoxSiege, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSuivantSiege)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelSiege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)))
                        .addGap(106, 106, 106))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnRetourSiege))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSiege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(lblChoxSiege, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetourSiege)
                    .addComponent(btnSuivantSiege))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuivantSiegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantSiegeActionPerformed
        // TODO add your handling code here:
        List<Integer> siegesChoisis = new ArrayList<>();

        for (JCheckBox cb : checkBoxes) {
            if (cb.isSelected()) {
                siegesChoisis.add((Integer) cb.getClientProperty("id_siege"));
            }
        }

        if (siegesChoisis.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner au moins un siège.");
            return;
        }

        if (siegesChoisis.size() > 5) {
            JOptionPane.showMessageDialog(this, "Vous ne pouvez choisir que 5 sièges maximum.");
            return;
        }

        parent.temp.placesChoisies = siegesChoisis;
        parent.temp.nb_billet = siegesChoisis.size();
        //System.out.println(parent.temp.nb_billet);

        parent.goTo("info_passager");

    }//GEN-LAST:event_btnSuivantSiegeActionPerformed

    private void btnRetourSiegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourSiegeActionPerformed
        // TODO add your handling code here:
        parent.goTo("choix_cooperative");
    }//GEN-LAST:event_btnRetourSiegeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetourSiege;
    private javax.swing.JButton btnSuivantSiege;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblChoxSiege;
    private javax.swing.JPanel panelSiege;
    // End of variables declaration//GEN-END:variables

}
