/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion_transport.swing.formulaires.panels;

//import com.sun.jdi.connect.spi.Connection;
import gestion_transport.swing.classes.ReservationTemp;
import gestion_transport.swing.formulaires.FormulaireReservationPassager;
import gestion_transport.swing.gestions.GestionReservation;
import gestion_transport.swing.gestions.GestionTrajet;
import java.sql.ResultSet;
import java.util.UUID;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;

/**
 *
 * @author Vanilah
 */
public class PanelPaiement extends javax.swing.JPanel {

    public FormulaireReservationPassager parent;
    /**
     * Creates new form PanelPaiement
     */
    public PanelPaiement(FormulaireReservationPassager parent) {
        initComponents();
        this.parent = parent;
        //afficherMontant();
    }

    public void afficherMontant() {
        try{
            GestionTrajet gt = new GestionTrajet();
            ResultSet rs = gt.selectPrixBillet(parent.temp.idTrajet);

            if (rs.next()) {
                double prix = rs.getDouble("prix_billet");
                double montantTotal = prix * parent.temp.nb_billet;
                parent.temp.montantPaye = montantTotal;
                lblMontantP.setText("Montant à payer : " + montantTotal + " Ar");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

        
    public void insererReservationPassager(){
        ReservationTemp temp = new ReservationTemp(parent.temp.idTrajet, parent.temp.nb_billet, parent.temp.nomClient, parent.temp.prenomClient, parent.temp.contactClient, parent.temp.montantPaye, parent.temp.transactionId, parent.temp.statut_p);
        try{
            GestionReservation gr = new GestionReservation();
            gr.insertReservationPassager(temp);
            JOptionPane.showMessageDialog(this, "Réservation enregistré avec succès !!");
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur lors de l'insertion de la réservation");
        }
    }
    
    
    public void reserverSieges(ReservationTemp temp) {
        try(Connection con = DriverManager.getConnection("jdbc:mysql://localhost/gestion_transport", "root", "");
            Statement st = con.createStatement()) 
        {
            // Convertit la liste en une chaîne "1, 2, 3, ..."
            String numeros = temp.placesChoisies.stream().map(String::valueOf).collect(Collectors.joining(","));

            String sql = "UPDATE siege  SET etat_siege = 'réservé' WHERE id_siege IN (" + numeros + ")";
             
            st.executeUpdate(sql);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void loadDataPaiem(){
        afficherMontant();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMontantP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMontantAPayer = new javax.swing.JTextField();
        btnPayer = new javax.swing.JButton();
        btnRetourPaim = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroMVola = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        jLabel1.setText("Procédure de paiement");

        jLabel2.setText("Entrer le montant");

        txtMontantAPayer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontantAPayerKeyTyped(evt);
            }
        });

        btnPayer.setText("Payer");
        btnPayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayerActionPerformed(evt);
            }
        });

        btnRetourPaim.setText("Retour");
        btnRetourPaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourPaimActionPerformed(evt);
            }
        });

        jLabel3.setText("Numéro MVola valide");

        txtNumeroMVola.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroMVolaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnRetourPaim)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPayer))
                        .addComponent(lblMontantP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(77, 77, 77))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(54, 54, 54)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMontantAPayer)
                                .addComponent(txtNumeroMVola, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMontantP, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMontantAPayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroMVola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetourPaim)
                    .addComponent(btnPayer))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayerActionPerformed
        // TODO add your handling code here:
            try {
                double montantEntre = Double.parseDouble(txtMontantAPayer.getText());
                String numero = txtNumeroMVola.getText();
                if (montantEntre == parent.temp.montantPaye ) {
                    parent.temp.montantPaye = montantEntre;
                    if(!numero.matches("03[48]\\d{7}")){
                        JOptionPane.showMessageDialog(this, "Numéro MVola invalide !");
                        return;
                    }else{
                        String fakeTransactionId= "MV-"+UUID.randomUUID().toString().substring(0, 8);
                        parent.temp.transactionId = fakeTransactionId;
                        parent.temp.statut_p ="Payé";
                        JOptionPane.showMessageDialog(this, "Paiement validé.");
                        insererReservationPassager();
                        //ReservationTemp temp = new ReservationTemp();
                        reserverSieges(parent.temp);
                        parent.goTo("facture");
                    }                   
                } else {
                    JOptionPane.showMessageDialog(this, "Montant incorrect !");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Veuillez entrer un montant valide.");
            }

    }//GEN-LAST:event_btnPayerActionPerformed

    private void btnRetourPaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourPaimActionPerformed
        // TODO add your handling code here:
        parent.goTo("infoclient");
    }//GEN-LAST:event_btnRetourPaimActionPerformed

    private void txtMontantAPayerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontantAPayerKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtMontantAPayerKeyTyped

    private void txtNumeroMVolaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroMVolaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
        if(txtNumeroMVola.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroMVolaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayer;
    private javax.swing.JButton btnRetourPaim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMontantP;
    private javax.swing.JTextField txtMontantAPayer;
    private javax.swing.JTextField txtNumeroMVola;
    // End of variables declaration//GEN-END:variables
}
